### ISSUE TITLE
Mention multiple datasource in TWO_TASKS 

### ISSUE THREAD

**Issue by ishanroy** [paypal/hera#112]
Hi, I wanted to know is there support for multiple datasource in hera and if so, how can we mention it using the TWO_TASKS parameter as presently it is accepting only one connection detail as mentioned in the [page.](https://github.com/paypal/hera/blob/master/docs/configuration.md#two_task). There is option to mention different shards but if we want connectivity to different databases, how to do the same.

**Comment by ModEtchFill** [comment]
For the read-replica query failover, the failover database would be TWO_TASK_STANDBY0.

For MySQL failover, two pipes to separate entries, tcp(127.0.0.1:3306)/myschema?timeout=9s||tcp(127.0.0.2:3306)/myschema

I'm not sure if those cover how you'd like to use different databases.
