### ISSUE TITLE
Inconsistency in event names of CAL log

### ISSUE THREAD

**Issue by stephanievu** [paypal/hera#123]
**What I Did**
I sent an insert operation with huge pay load > 1MB, then perform a select to get back item 

**What I Expected**
HERAMUX should be used for hera event names to report large_payload

**What I Saw Instead**
large_payload_in/out have different event names
E13:29:29.31    MUX     large_payload_in        0       len=3145857
E13:29:33.51    HERAMUX large_payload_out       0       len=3145753

**Comment by shtiencode** [comment]
This was fixed in commit 1114007f6d3be29e70437f5f9db1e9d6c7d839ef
