### ISSUE TITLE
Remove dead config

### ISSUE THREAD

**Issue by ModEtchFill** [paypal/hera#150]
Some config like EnableConnLimit isn't used anywhere and can be removed.

*What I Did*
I was searching for the db connection limiting.

*What I Saw*
I ran into EnableConnLimit in config.go

*What I Expect*
I wanted to find the MaxDbConnPerSec.

**Comment by Keenal** [comment]
I'd like to take this for Hacktoberfest!

**Comment by ModEtchFill** [comment]
@Keenal Go for it
