### ISSUE TITLE
configuration value set on backlog_pct in occ.txt is not considered

### ISSUE THREAD

**Issue by varuntechie** [paypal/hera#2]
Although backlog_pct=0. hera allows many requests in bklg queue.
    grep backlog occ.txt
    backlog_pct = 0
    request_backlog_timeout = 60000

State.log:
05/01/2019 17:01:22: ----------- init acpt wait busy schd fnsh quce asgn idle bklg strd
05/01/2019 17:01:22: occ 0 0 0 0 0 0 1 0 0 9 0
05/01/2019 17:01:23: occ 0 0 0 0 0 0 1 0 0 9 0
05/01/2019 17:01:24: occ 0 0 0 0 0 0 1 0 0 9 0

**Comment by stephanievu** [comment]
Testing issue. backlog_pct works fine
