### ISSUE TITLE
MySQL and Postgre error code for TAF

### ISSUE THREAD

**Issue by shtiencode** [paypal/hera#241]
**What I Did**

I read the coordinatortaf.go to understand what error TAF will kick in.

**What I See**

I don't see compatible error codes specific for MySQL and Postgre

**What I Expect**

There is the list of errors defined for MySQL and Postgre to kick in TAF retry.

**Comment by ModEtchFill** [comment]
Our experience with read-replica-retry (transparent application failover [taf]) is all the primary connections become busy and queries then go to the secondary. This happens on a sub-second timescale and can resolve under a second if the primary db recovers sufficiently quickly.
