### ISSUE TITLE
Tracing Logs

### ISSUE THREAD

**Issue by ModEtchFill** [paypal/hera#25]
We are starting with github.com/paypal/hera/cal which can time areas of code and also log events. In hera, we direct this to a file. In PayPal, we direct it to reporting infrastructure which gives graphs for duration, error, and count. We found it useful for monitoring.

In the future, we'd like to add our monitoring and scaling tools to open source hera. We will be investigating various tools and code interfaces to make a successful change.  We would expect any replacement to have significant backward compatibility.

**Comment by ajlin179** [comment]
Hera team started looking into Opentelemetry for addressing monitoring and observability feature so that Hera no need to change monitoring API  and point to actual Logging/Monitoring platform available in deployment environment by configuration setup .

**Comment by ModEtchFill** [comment]
Please look at the otel branch for some early development
