### ISSUE TITLE
MySQL: java setObject() to set time does not work

### ISSUE THREAD

**Issue by stephanievu** [paypal/hera#5]
This works fine with Oracle DB but does not work with MySQL  DB. After setting time with setObject(), I get back time of 00:00:00

**What I Did**
Java codes:
Statement st = dbConn.createStatement();
PreparedStatement pst = dbConn.prepareStatement(
"insert into jdbc_occ_test (id, int_val, str_val, char_val, float_val, raw_val, blob_val, clob_val, date_val, "
+ "time_val, timestamp_val, timestamp_tz_val) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
......
pst.setObject(10, new Time(now).toString(), Types.TIME);
pst.executeUpdate();
....

ResultSet rs = st.executeQuery( "select id, int_val, str_val, char_val, float_val, raw_val, blob_val, " +
				"clob_val, date_val, time_val, timestamp_val from jdbc_occ_test where id=" + iID_START);
rs.next();
System.out.println ("Time is " +  rs.getTime(10).toString());

**What I Expected**
Results:
Inserted time: 10:49:32
Time getting back: 10:49:32

**What I Saw Instead**
Results:
Inserted time: 10:49:32
Time getting back: 00:00:00

**Comment by ModEtchFill** [comment]
Issue used setObject() while the revised test used setString()

**Comment by ModEtchFill** [comment]
Team concluded not-a-bug. 

The DATE type is used for values with a date part but no time part. MySQL retrieves and displays DATE values in 'YYYY-MM-DD' format.
