### ISSUE TITLE
CLIENT_INFO in CAL log has status "unset"

### ISSUE THREAD

**Issue by stephanievu** [paypal/hera#7]
**What I Did**
I send requests to server

**What I See**
unset is not expected as a "status" of CLIENT_INFO
17:06:54.75 CLIENT_INFO unset 0 mux&PoolStack=stvu.pg_occ:CalThreadId=0TopLevelTxnStartTime=TopLevelTxn not set*Host=hyperlvs19&corr_id=NotSet

**What I Expect**
unset should not be there, status of 0, or 1 or 2...should be seen

**Comment by sssinghsyr** [comment]
java and go driver send default pool name value.

https://github.com/paypal/hera/blob/30fca1a6c346187c04888f24870d7b8a73b5927d/client/java/jdbc/src/main/java/com/paypal/hera/cal/CalClientConfigMXBeanImpl.java#L10

https://github.com/paypal/hera/blob/30fca1a6c346187c04888f24870d7b8a73b5927d/client/gosqldriver/tcp/driver.go#L73

Currently drivers do not include config file.
