### ISSUE TITLE
Multiple clients (threads) cannot insert rows into same table using Transaction

### ISSUE THREAD

**Issue by stephanievu** [paypal/hera#79]
**What I Did**
I ran test to do insert in same table with multiple threads using Transaction

**What I Expected**
I should not get any error, insertion should work fine for multiple threads

What I Saw Instead
Insert operation fails with error:
16:23:15.290132 warn: [WORKER 4 adapter.go:184] mysql ProcessError Error 1205: Lock wait timeout exceeded; try restarting transaction sqlHash:3295891924 Cmd:4 errno:1205
16:23:15.290508 warn: [WORKER 4 cmdprocessor.go:404] Execute error: Error 1205: Lock wait timeout exceeded; try restarting transaction

Note that if I don't use transaction, the test works fine

**Comment by ModEtchFill** [comment]
What's the table definition?  There's a few locks to investigate (https://dev.mysql.com/doc/refman/8.0/en/innodb-locks-set.html).

**Comment by stephanievu** [comment]
I no longer see the issue in latest codes. Close it
