### ISSUE TITLE
Send an explicit cancel request to the database instead of abandoning the connection

### ISSUE THREAD

**Issue by cornellb** [paypal/hera#91]
As I understand, the current way to deal with long running queries is to close the respective db connections (and create new ones to still maintain the configured pool size).

It should be more performant to send explicit cancel requests to the db. Some more info in the link below.
https://asktom.oracle.com/m/pls/asktom/asktom.search?tag=cancelling-long-running-queries

**Comment by ModEtchFill** [comment]
We're working on merging a few more capabilities from our legacy oracleworker.  This includes OCIBreak() canceling functionality.
